---

- name: Insert environment variables locally
  hosts: localhost
  connection: local
  
  vars:
    - profile: ~/.zshenv
  vars_files:
    - vars/env_vars.json
  
  tasks:
    - name: Create profile file - if it doesn't exist
      copy:
        content: ""
        dest: "{{ profile }}"
        force: no
    
    - name: Insert environment variables
      lineinfile:
        path: "{{ profile }}"
        state: present
        regex: "^{{ item.key }}="
        line: 'export {{ item.key|upper }}="{{ item.value }}"'
      with_items: "{{ env_vars }}"